# Generated by Django 3.0.3 on 2020-05-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
