# Generated by Django 3.0.3 on 2020-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0003_auto_20200511_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
