# Generated by Django 3.0.3 on 2020-05-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0004_auto_20200511_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
