# Generated by Django 3.0.3 on 2020-06-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0007_friendlist_friend_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='friend_request',
            new_name='friend_request_sent',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friend_request_received',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
