# Generated by Django 3.0.3 on 2020-06-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0009_auto_20200607_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
