# Generated by Django 3.0.3 on 2020-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0013_auto_20200607_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friend_request_received',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friend_request_sent',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
