# Generated by Django 3.0.3 on 2020-06-17 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapApp', '0014_auto_20200607_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(max_length=150)),
                ('notification_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_received', to=settings.AUTH_USER_MODEL)),
                ('notification_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
