# Generated by Django 3.0.3 on 2020-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0018_auto_20200617_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlist',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
    ]
