# Generated by Django 3.0.3 on 2020-07-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0019_notificationlist_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
