# Generated by Django 3.0.3 on 2020-07-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0020_friendlist_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='is_approved',
        ),
    ]
