# Generated by Django 3.0.3 on 2020-07-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0021_remove_friendlist_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friend_request_sent',
        ),
    ]
