# Generated by Django 3.0.3 on 2020-07-12 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapApp', '0022_remove_friendlist_friend_request_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friend_request_received',
        ),
        migrations.CreateModel(
            name='FriendApplicationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField(default=False)),
                ('isBlackListed', models.BooleanField(default=False)),
                ('friend_request_received', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('friend_request_sent', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
